#!/usr/bin/env bash

#set -x # for debug mode
set -euo pipefail

base_sober_dir=~/.var/app/org.vinegarhq.Sober/
sober_dir=$base_sober_dir/data/sober/
sobercookie_dir="$XDG_DATA_HOME/sobercookie"
cookie_dir="$sobercookie_dir/cookies"
data_dir="$sobercookie_dir/data"
config_file="$XDG_CONFIG_HOME/sobercookie.conf"

help_fn() {
   echo "available options are:"
   echo "launch [name] [sober arguments] -- launches sober using cookie"
   echo "save [name] -- save current sober cookie"
   echo "load [name] -- load cookie to sober"
   echo "rm [name] -- remove saved cookie"
   echo "unload -- log out of sober without invalidating cookie"
   echo "clean -- remove all cookies and configurations"
   echo "list [--show-hidden] -- list all saved cookies"
}

if [[ ! -v 1 ]]; then
   echo "no argument supplied"
   help_fn
   exit
fi

## load config (if it exists)
# shellcheck source=/dev/null
[[ -e "$config_file" ]] && . "$config_file"

if [[ ! -d "$sober_dir" ]]; then
   echo "\$sober_dir [$sober_dir] does not exist"
   exit
fi

for dir in "$cookie_dir" "$data_dir"; do
   if [[ ! -d "$dir" ]]; then
      read -rp "[$dir] does not exist, do you wish to create it? [Y/n]: " ans
      if [[ "$ans" == "y" || "$ans" == "Y" || "$ans" == "" ]]; then
         echo "creating $dir"
         mkdir -p "$dir"
      else
         echo "cannot continue without cookie directory"
         exit
      fi
   fi
done

save_fn() {
   if [[ ! -v 1 ]]; then
      echo "please supply the name you want to give to this cookie"
      exit
   fi
   cp "$sober_dir/cookies" "$cookie_dir/$1"
   echo "saved $1"
}

load_fn() {
   if [[ ! -v 1 ]]; then
      echo "please supply the name of the cookie you want to load"
      exit
   fi
   cp "$cookie_dir/$1" "$sober_dir/cookies"
}

list_fn() {
   ls -1 $([[ -v 1 && $1 == "--show-hidden" ]] && echo "-A") "$cookie_dir"
}

rm_fn() {
   if [[ ! -v 1 ]]; then
      echo "please supply the name of the cookie you want to remove"
      exit
   fi
   rm "$cookie_dir/$1"
}

unload_fn() {
   rm "$sober_dir/cookies"
   echo successfully unloaded cookie
}

clean_fn() {
   read -rp "are you sure you want to remove all saved cookies and configurations? [y/N]" ans
   if [[ "$ans" == "y" || "$ans" == "Y" ]]; then
      rm -r "$cookie_dir"
      echo "removed $cookie_dir"
      rm -r "$config_file"
      echo "removed $config_file"
   fi
}

launch_fn() {
   if [[ ! -v 1 ]]; then
      echo "please supply the name of the cookie you want to launch using"
      exit
   fi

   SANDBOX_DIR=$(mktemp -d -t sober-instance-XXXXXX)
   trap 'rm -rf "$SANDBOX_DIR"' EXIT
   mkdir -p "$SANDBOX_DIR"
   cp -r "$base_sober_dir"/* "$SANDBOX_DIR"

   if [[ $1 != "default" ]]; then
      cp "$cookie_dir/$1" "$SANDBOX_DIR/data/sober/cookies"
   fi

   shift

   bwrap --dev-bind / / --bind $SANDBOX_DIR $base_sober_dir flatpak run org.vinegarhq.Sober $@
}

case $1 in
   "save")   shift && save_fn   "$@" ;;
   "load")   shift && load_fn   "$@" ;;
   "list")   shift && list_fn   "$@" ;;
   "rm")     shift && rm_fn     "$@" ;;
   "unload") shift && unload_fn "$@" ;;
   "clean")  shift && clean_fn  "$@" ;;
   "launch") shift && launch_fn "$@" ;;
   *) help_fn ;;
esac
