#!/usr/bin/env bash

# set -x # for debug mode
set -euo pipefail

sober_dir=~/.var/app/org.vinegarhq.Sober/data/sober/
sobercookie_dir="$XDG_DATA_HOME/sobercookie"
cookie_dir="$sobercookie_dir/cookies"
data_dir="$sobercookie_dir/data"
sober_id="org.vinegarhq.Sober"
sober_cmd="flatpak run $sober_id"
sober_kill_cmd="flatpak kill $sober_id"

help_fn() {
   echo "available options are:"
   echo "launch [name] [--foreground] [arguments] -- launches sober using cookie"
   echo "save [name] -- save current sober cookie"
   echo "load [name] -- load cookie to sober"
   echo "rm [name] -- remove saved cookie"
   echo "unload -- log out of sober without invalidating cookie"
   echo "clean -- remove all saved cookies"
   echo "list -- list all saved cookies"
}

if [[ ! -v 1 ]]; then
   echo "no argument supplied"
   help_fn
   exit
fi

if [[ ! -d "$sober_dir" ]]; then
   echo "\$sober_dir [$sober_dir] does not exist"
   exit
fi

for dir in "$cookie_dir" "$data_dir"; do
   if [[ ! -d "$dir" ]]; then
      read -p "[$dir] does not exist, do you wish to create it? [Y/n]: " ans
      if [[ "$ans" == "y" || "$ans" == "Y" || "$ans" == "" ]]; then
         echo "creating $dir"
         mkdir -p "$dir"
      else
         echo "cannot continue without cookie directory"
         exit
      fi
   fi
done


save_fn() {
   if [[ ! -v 1 ]]; then
      echo "please supply the name you want to give to this cookie"
      exit
   fi
   cp "$sober_dir/cookies" "$cookie_dir/$1"
   echo saved $1
}

load_fn() {
   if [[ ! -v 1 ]]; then
      echo "please supply the name of the cookie you want to load"
      exit
   fi
   cp "$cookie_dir/$1" "$sober_dir/cookies"
}

list_fn() {
   ls -1 $([[ -v 1 && $1 == "--show-hidden" ]] && echo "-A") "$cookie_dir"
}

rm_fn() {
   if [[ ! -v 1 ]]; then
      echo "please supply the name of the cookie you want to remove"
      exit
   fi
   rm "$cookie_dir/$1"
}

unload_fn() {
   rm "$sober_dir/cookies"
   echo successfully unloaded cookie
}

clean_fn() {
   read -p "this will remove all saved cookies ($cookie_dir), do you wish to continue? [y/N]: " ans
   if [[ "$ans" == "y" || "$ans" == "Y" ]]; then
      rm -r "$cookie_dir"
      echo "removed $cookie_dir"
   fi
}

launch_fn() {
   if [[ ! -v 1 ]]; then
      echo "please supply the name of the cookie you want to launch using"
      exit
   fi

    # Patching out the multi instance check :P
   [[ ! -f "$data_dir/latest" ]] && touch "$data_dir/latest"
   current_ver=$(flatpak info "$sober_id" -c)
   if [[ "$current_ver" != "$(cat "$data_dir/latest")" ]]; then
      echo "$current_ver" > "$data_dir/latest"
      perl -i -pne \
         's/\xe8\xb5\x90\xfb\xff\x89\xc5/\xbd\x01\x00\x00\x00\x90\x90/' \
         "$XDG_DATA_HOME/flatpak/app/$sober_id/current/active/files/bin/sober"
   fi

   if [[ -e "$sober_dir/cookies" ]]; then
      saved=/tmp/tmp_saved_sober_cookie
      cp -f "$sober_dir/cookies" "$saved"
      trap "cp -f \"$saved\" \"$sober_dir/cookies\" ; rm -f -- $saved" EXIT
   fi

   if [[ $1 == "--foreground" ]]; then
      shift
      foreground=
   fi

   if [[ $1 != "default" ]]; then
      load_fn $@
   fi

   shift

   if [[ -v foreground ]]; then
      exec $sober_cmd $@
   else
      eval $sober_cmd $@ &>/dev/null &
      sleep 2
   fi
}

case $1 in
   "save")   shift && save_fn   $@ ;;
   "load")   shift && load_fn   $@ ;;
   "list")   shift && list_fn   $@ ;;
   "rm")     shift && rm_fn     $@ ;;
   "unload") shift && unload_fn $@ ;;
   "clean")  shift && clean_fn  $@ ;;
   "launch") shift && launch_fn $@ ;;
   *) help_fn ;;
esac
